GET https://botmanager-v2-api.herokuapp.com/


###
GET https://botmanager-v2-api.herokuapp.com/api/bots

###
GET https://bm-v2-api.onrender.com/api/bots

###
GET https://bm-v2-api.onrender.com/api/

###
PUT https://botmanager-v2-api.herokuapp.com/api/bot
Content-Type: application/json

{
    "email":"testing@mail.com",
    "location":"testing",
    "error":"testing",
    "status":true,
    "requestedStatus":true
}


###
GET https://botmanager-v2-api.herokuapp.com/api/bot/id/6050ce66f98c522ad8d10ffe


###
GET https://botmanager-v2-api.herokuapp.com/api/bot/email/vladimir@mail02.com


###
DELETE https://botmanager-v2-api.herokuapp.com/api/bot/id/605292cf9702ec003119479b


###
DELETE https://botmanager-v2-api.herokuapp.com/api/bot/email/mail@mail.ru


###
POST https://botmanager-v2-api.herokuapp.com/api/user
Authorization: Basic dmxhZGltaXIudkBnbWFpbC5jb206dnZ2

###
POST https://bm-v2-api.onrender.com/api/user/me
Authorization: Basic Ym1fdjJfYWRtaW5AcHJvdG9ubWFpbC5jb206dnZ2dg==

###
PUT https://bm-v2-api.onrender.com/api/user
Content-Type: application/json

{
    "email": "maasheenu@gmail.com",
    "password" : "password"
}
###

PUT https://botmanager-v2-api.herokuapp.com/api/user
Content-Type: application/json

    {
        "email": "vavan.v@gmail.com",
        "password" : "vvvv",
        "isAdmin": true
    }


###
GET  https://botmanager-v2-api.herokuapp.com/api/bot/requestedStatus/vladimir@mail.com


###
POST https://botmanager-v2-api.herokuapp.com/api/bot/requestedStatus/vladimir@mail.com
Content-Type: application/json

{
    "requestedStatus":true
}


###
GET  https://botmanager-v2-api.herokuapp.com/api/bot/requestedStatus/vladimir@mail202.casom


###
GET https://botmanager-v2-api.herokuapp.com/api/files


###
GET https://botmanager-v2-api.herokuapp.com/api/file/express-handbook.pdf


###
DELETE https://botmanager-v2-api.herokuapp.com/api/delete/.txt

###
GET https://botmanager-v2-api.herokuapp.com/api/md5/get

{
    "key":"YG4I69OGDUGSZVQCAGYUYZKPTMG4I7FN",
    "hd_id":"6050ce66f98c522ad8d10ffe",
    "code":"ALBION",
    "name":"Albion_Online.exe"
}

maasheenu@gmail.com

###
POST https://bm2.herokuapp.com/api/file/get
Content-Type: application/json

{
    "code":"NWRLD",
    "name":"launcher.exe"
}

###
GET https://bm2.herokuapp.com/api/md5/61588602e09a640016ed6ff6

###
POST https://bm2.herokuapp.com/api/bot/days
Content-Type: application/json

{
    "key":"8RRZL4Z1VP0OZHXZQ49WP0KPI080J3Z2",
}


###
GET  https://gmv22api.herokuapp.com/api/bot/ping
Content-Type: application/json

{
    "key":"B6DWJDXDGENNJSY8UB4DKO7QAN876HWZ",
    "hd_id":"62eb9877304765520b587382fca8f48b"
}


100.20.92.101
44.225.181.72
44.227.217.144

###
GET https://100.20.92.101/api/

###
GET https://44.225.181.72/api/

###
GET https://44.227.217.144/api/


###
GET https://bm-v2-api.onrender.com/api/


###
GET https://bm-v2-api.onrender.com/api/md5/get
Content-Type: application/json

{
    "key":"YG4I69OGDUGSZVQCAGYUYZKPTMG4I7FN",
    "hd_id":"6050ce66f98c522ad8d10ffe",
    "code":"ALBION",
    "name":"Albion_Online.exe"
}

###
GET https://bm-v2-api.onrender.com/api/bots


###
GET https://bm-v2-api.onrender.com/api/license/days
Content-Type: application/json

{
    "key":"7E4NA3581M2OFL0RSUJ9P759PY1PCVRZ",
    "hd_id":"6050ce66f98c522ad8d10ffe"
}

###
GET http://localhost:8081/api/license/days
Content-Type: application/json

{
    "key":"7E4NA3581M2OFL0RSUJ9P759PY1PCVRZ",
    "hd_id":"6050ce66f98c522ad8d10ffe"
}